### ISSUE TITLE
Resolution 857: Official web access for ISO/TC 211 resources to support implementation of standards

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/Resources#3]
> “ISO/TC 211 resolves to use isotc211.org for web access to its official resources that support implementation, including but not limited to, XML Implementation Schemas, XML Codelists, XML Example files, Ontologies, UML XMI files, Terminologies and Profiles of standards.”

Link to previous discussion (team members only): https://github.com/orgs/ISO-TC211/teams/resources/discussions/1

**Comment by jetgeo** [comment]
I originally uploaded three figures: 
1. Overview of the [current situation](https://github.com/ISO-TC211/Resources/blob/master/Illustrations/Now.png)
2. Possible scenario A with [isotc211.org as repository for everything](https://github.com/ISO-TC211/Resources/blob/master/Illustrations/ScenarioA.png)
3. Possible scenario B with [continued use of the JRC SVN repo and GitHub](https://github.com/ISO-TC211/Resources/blob/master/Illustrations/ScenarioB.png)

Scenario A will require that whoever runs the isotc211.org server also maintains user software and user accounts for Subversion and Git. 

My suggestion is to use the structure shown in the new figure bellow. This means scenario B from above - we continue to use SVN at JRC and GIT at GitHub for live work, and use isotc.211.org as the official repository.
![resourcesstructure](https://user-images.githubusercontent.com/7501876/38664747-c1a51eb8-3e3a-11e8-9d29-862d5ba5b011.png)

**Comment by PeterParslow** [comment]
I'm pretty sure I've mentioned this elsewhere, but I do feel that this resolution clashes with ISO TMB resolution 38/2017 (https://isotc.iso.org/livelink/livelink/fetch/-15620806/15620808/15623592/15768654/TMB_resolutions_%2D_2017_%28Resolution_1%2D135%29.pdf?nodeid=18628999&vernum=-2), which accepts that even normative parts of ISO standards can be stored in machine readable formats on the standards.iso.org site, so long as they follow the same maintenance/revision process as the "traditional" PDF standard or as a registered Maintenance agency or Registration authority.

I don't think that anyone at TC211 in Wellington was aware of that TMB resolution.

**Comment by PeterParslow** [comment]
Whoops - wrong GitHub button

**Comment by jetgeo** [comment]
Peter;
I am not sure the resolution you refer to clashes with our resolution. I see it only as a clarification of the requirements for using URL is ISO standards, and I believe we fullfill all four requirements. 
But I will include the resolution in my report.

**Comment by PeterParslow** [comment]
I didn’t mean to imply it clashes. I think it is a useful hook to hang our intentions on – evidence that at least (at last?) ISO is taking the web a bit seriously!

Peter Parslow
Open Standards Lead
Adanac Drive, Southampton, United Kingdom, SO16 0AS
T: +44 (0)2380 055341 | M: +44 (0)7796 610020
www.os.uk<http://os.uk/> | peter.parslow@os.uk<mailto:peter.parslow@os.uk>

**Comment by tedhabermann** [comment]
Running git on the isotc211 server as a mechanism for updating content there is an option that we should keep open. No user accounts required... I'm not sure how to make this comment a root of a new thread...

**Comment by jetgeo** [comment]
Point number 3 in the attached communique from ISO TMB is relevant for this work:

> **Strategic Advisory Group on Machine-readable standards**
**Background:** Working Group 5 of the TF on Alternative standardization processes explored how ISO should tackle the challenge of developing machine-readable standards. It its final report to the TMB, it recommended setting up a Strategic Advisory Group (SAG) to develop a roadmap on the introduction and implementation of machine-readable standards within ISO, including identifying ISO standards that are a priority for transformation from text into machine-readable standards. The SAG’s mandate also includes the development guidelines for technical committees and provision of input on the subject for the next ISO Strategic Plan 2021-2025. The SAG will include representatives from CPAG, ITSAG, and IEC.
The TMB approved the creation of this SAG via TMB Resolution 94/2018. See the Resolution for full details of the SAG’s mandate and membership.
**What this means for you:** Are you interested in the evolution of machine-readable standards in ISO? Updates on the progress of this SAG will be provided in future editions of the TMB Communiqué. For questions or further information, you can contact the TMB Secretariat on tmb@iso.org.> 


[TMB_Communiqué Issue Nr 60 (September 2018).pdf](https://github.com/ISO-TC211/Resources/files/2438846/TMB_Communique.Issue.Nr.60.September.2018.pdf)

**Comment by PeterParslow** [comment]
I was also interested to read this, which is an 'approved recommendation' from ISO/IEC JTC1's Joint Advisory Committee, who clearly spent some time recently discussing this move in TMB:

>Recommendation 14 – **Request to ISO and IEC concerning Uniform Resource
Identifiers**
The JTC 1 JAG requests ISO and IEC to provide URIs (Uniform Resource Identifiers) and to
host corresponding content to meet the needs of certain standards:
- Modern technology standards benefit from inclusion of auxillary or reference
information (e.g., code, human interface information) which are not feasible to fully
describe in a standard itself and as a result, the ability to include references in the
standard is essential.
- Such references are best implemented using URIs and this need was identified by
JTC 1/SC 36 where this auxiliary information is required to permit the standard to
be used in specific language contexts (in this case, to permit the referencing of
linguistic identifiers in ISO/IEC 19788).
- (Requirement:) The URIs need to be valid for a long time (many years, i.e. for the
duration of the underlying standard) without being changed, and standards users
will expect that the information returned is authentic and traceable to the actual
ISO/IEC standard. For example, while the current “standards.iso.org” website might
be considered, this site would need to be secured so that the returned information
can be authenticated. Furthermore, ISO and IEC together might consider a joint URI
domain rather than using unique ISO and IEC domains for use by joint ISO/IEC
standards.
While ISO has identified the need to support permanent references, ISO's implementation
does not fully support the needs of technology standards. JTC 1 would welcome the
opportunity to work with ISO and IEC to consider solutions to the needs identified across a
broad range of ISO and IEC standards.

extract from https://isotc.iso.org/livelink/livelink?func=ll&objId=19902003&objAction=Open (which should open without logging in to Livelink)
